name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: official
      url: https://log.kj415j45.space/
    steps:
      - uses: actions/checkout@v3
      - name: Write wrangler configure file
        run: echo ${{ secrets.WRANGLER_FILE }} | base64 --decode > wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            wrangler d1 execute log --file=./schema.sql
        env:
          NO_D1_WARNING: true
