name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: official
      url: https://log.kj415j45.workers.dev/
    steps:
      - uses: actions/checkout@v3
      - name: Write wrangler configure file
        run: echo ${{ secrets.WRANGLER_FILE }} | base64 --decode > wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
